#include "Ipv4.h"

const char* ipv4_numbers[] = {
	"IPv6 Hop-by-Hop Option	(HOPOPT)",
	"Internet Control Message (ICMP)",
	"Internet Group Management (IGMP)",
	"Gateway-to-Gateway (GGP)",
	"IPv4 encapsulation	(IPv4)",
	"Stream (ST)",
	"Transmission Control (TCP)",
	"CBT",
	"Exterior Gateway Protocol (EGP)",
	"any private interior gateway (used by Cisco for their IGRP) (IGP)",
	"BBN RCC Monitoring	(BBN-RCC-MON)",
	"Network Voice Protocol	(NVP-II)",
	"PUP",
	"ARGUS",
	"EMCON",
	"Cross Net Debugger	(XNET)",
	"Chaos (CHAOS)",
	"User Datagram Protocol (UDP)",
	"Multiplexing",
	"DCN",
	"TAC Monitoring",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"any local network",
	"SATNET and Backroom EXPAK",
	"MIT Subnet Support",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"SATNET Monitoring",
	"Unassigned",
	"Internet Packet Core Utility",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Backroom SATNET Monitoring",
	"Unassigned"
	"WIDEBAND Monitoring",
	"WIDEBAND EXPAK",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Unassigned",
	"Reserved"
};

Ipv4::Ipv4(const unsigned char* paquete, int tamanio){
  version_ihl = paquete[14];
  dscp_ecn = paquete[15];
  memcpy(&totalLength, &(paquete[16]), 2);
  totalLength = ntohs(totalLength);
  memcpy(&identification, &(paquete[18]), 2);
  identification = ntohs(identification);
  memcpy(&flags_fragmentOffset, &(paquete[20]), 2);
  flags_fragmentOffset = ntohs(flags_fragmentOffset);
  ttl = paquete[22];
  protocol = paquete[23];
  memcpy(&headerChecksum, &(paquete[24]), 2);
  headerChecksum = ntohs(headerChecksum);
  memcpy(direccionOrigen, &(paquete[26]), 4);
  memcpy(direccionDestino, &(paquete[30]), 4);
  tamanioExtraHeader = tamanio - 34;
}

void Ipv4::imprime(){
  unsigned char  temp;
  std::bitset<16> flags(flags_fragmentOffset);
  std::bitset<8>  ecn(dscp_ecn);
  temp = version_ihl >> 4;
  printf("Version:\t\t%u\n", temp);
  temp = version_ihl << 4;
  temp >>= 4;
  printf("IHL:\t\t\t%d (%d bytes)\n", temp, temp*4);
  temp = dscp_ecn >> 2;
  printf("DSCP:\t\t\t%d\n", temp);
  printf("ECN (bit 1):\t\t");
  determinaBitEncendidoApagado(ecn, 6);
  printf("ECN (bit 2):\t\t");
  determinaBitEncendidoApagado(ecn, 7);
  printf("Total length:\t\t%u\n", totalLength);
  printf("Identification:\t\t%u\n", identification);
  printf("More fragments:\t\t");
  determinaBitEncendidoApagado(flags, 14);
  printf("Don't fragments:\t");
  determinaBitEncendidoApagado(flags, 13);
  temp = flags_fragmentOffset << 3;
  printf("Fragment offset:\t%u\n", temp >> 3);
  printf("TTL:\t\t\t%d\n", ttl);
  printf("Protocol:\t\t%d (%s)\n", protocol, ipv4_numbers[protocol]);
  printf("Header checksum:\t0x%02X\n", headerChecksum);
  printf("Direccion origen:\t");
  imprimeDireccionIP(direccionOrigen);
  printf("Direccion destino:\t");
  imprimeDireccionIP(direccionDestino);
  printf("Carga util:\t\t%d bytes.\n", tamanioExtraHeader);
}
